// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards(
  id,
  front_content,
  back_content,
  interval,
  ease_factor,
  repetitions_count,
  last_reviewed_at,
  created_at,
  deck_id
) VALUES (
  gen_random_uuid(),
  $1,
  $2,
  1,
  2.5,
  0,
  NULL,
  NOW(),
  $3
) RETURNING 
  id,
  front_content,
  back_content,
  interval,
  ease_factor,
  repetitions_count,
  last_reviewed_at,
  created_at,
  deck_id
`

type CreateCardParams struct {
	FrontContent string
	BackContent  string
	DeckID       uuid.UUID
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard, arg.FrontContent, arg.BackContent, arg.DeckID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FrontContent,
		&i.BackContent,
		&i.Interval,
		&i.EaseFactor,
		&i.RepetitionsCount,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.DeckID,
	)
	return i, err
}

const deleteCards = `-- name: DeleteCards :exec
  DELETE FROM cards
`

func (q *Queries) DeleteCards(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCards)
	return err
}
