// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards(
  id,
  front_content,
  back_content,
  interval,
  target,
  ease_factor,
  repetitions_count,
  last_reviewed_at,
  last_reviewed_num,
  created_at,
  deck_id,
  tempo,
  perfect_streak,
  bad_streak
) VALUES (
  gen_random_uuid(),
  $1,
  $2,
  1,
  $3,
  2.5,
  0,
  NULL,
  0,
  NOW(),
  $4,
  $5,
  0,
  0
) RETURNING 
  id,
  front_content,
  back_content,
  interval,
  target,
  ease_factor,
  repetitions_count,
  last_reviewed_at,
  last_reviewed_num,
  created_at,
  deck_id,
  tempo,
  perfect_streak,
  bad_streak
`

type CreateCardParams struct {
	FrontContent string
	BackContent  string
	Target       int32
	DeckID       uuid.UUID
	Tempo        int32
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.FrontContent,
		arg.BackContent,
		arg.Target,
		arg.DeckID,
		arg.Tempo,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FrontContent,
		&i.BackContent,
		&i.Interval,
		&i.Target,
		&i.EaseFactor,
		&i.RepetitionsCount,
		&i.LastReviewedAt,
		&i.LastReviewedNum,
		&i.CreatedAt,
		&i.DeckID,
		&i.Tempo,
		&i.PerfectStreak,
		&i.BadStreak,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteCards = `-- name: DeleteCards :exec
DELETE FROM cards
`

func (q *Queries) DeleteCards(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCards)
	return err
}

const getCardById = `-- name: GetCardById :one
SELECT id, front_content, back_content, interval, target, ease_factor, repetitions_count, last_reviewed_at, last_reviewed_num, created_at, deck_id, tempo, perfect_streak, bad_streak FROM cards
WHERE id = $1
`

func (q *Queries) GetCardById(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardById, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FrontContent,
		&i.BackContent,
		&i.Interval,
		&i.Target,
		&i.EaseFactor,
		&i.RepetitionsCount,
		&i.LastReviewedAt,
		&i.LastReviewedNum,
		&i.CreatedAt,
		&i.DeckID,
		&i.Tempo,
		&i.PerfectStreak,
		&i.BadStreak,
	)
	return i, err
}

const getCardsByDeck = `-- name: GetCardsByDeck :many
SELECT id, front_content, back_content, interval, target, ease_factor, repetitions_count, last_reviewed_at, last_reviewed_num, created_at, deck_id, tempo, perfect_streak, bad_streak FROM cards
WHERE deck_id = $1
`

func (q *Queries) GetCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.FrontContent,
			&i.BackContent,
			&i.Interval,
			&i.Target,
			&i.EaseFactor,
			&i.RepetitionsCount,
			&i.LastReviewedAt,
			&i.LastReviewedNum,
			&i.CreatedAt,
			&i.DeckID,
			&i.Tempo,
			&i.PerfectStreak,
			&i.BadStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET  front_content = $1,
  back_content = $2,
  interval = $3,
  target = $4,
  ease_factor = $5,
  repetitions_count = $6,
  last_reviewed_at = $7,
  last_reviewed_num = $8,
  tempo = $9,
  perfect_streak = $10,
  bad_streak = $11
WHERE id = $12
RETURNING id, front_content, back_content, interval, target, ease_factor, repetitions_count, last_reviewed_at, last_reviewed_num, created_at, deck_id, tempo, perfect_streak, bad_streak
`

type UpdateCardParams struct {
	FrontContent     string
	BackContent      string
	Interval         int32
	Target           int32
	EaseFactor       float64
	RepetitionsCount int32
	LastReviewedAt   sql.NullTime
	LastReviewedNum  int32
	Tempo            int32
	PerfectStreak    int32
	BadStreak        int32
	ID               uuid.UUID
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.FrontContent,
		arg.BackContent,
		arg.Interval,
		arg.Target,
		arg.EaseFactor,
		arg.RepetitionsCount,
		arg.LastReviewedAt,
		arg.LastReviewedNum,
		arg.Tempo,
		arg.PerfectStreak,
		arg.BadStreak,
		arg.ID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FrontContent,
		&i.BackContent,
		&i.Interval,
		&i.Target,
		&i.EaseFactor,
		&i.RepetitionsCount,
		&i.LastReviewedAt,
		&i.LastReviewedNum,
		&i.CreatedAt,
		&i.DeckID,
		&i.Tempo,
		&i.PerfectStreak,
		&i.BadStreak,
	)
	return i, err
}
