// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (id, title, description, created_at, user_id)
VALUES (
  gen_random_uuid(),
	$1,
	$2,
  NOW(),
  $3
)
RETURNING id, title, description, created_at, user_id
`

type CreateDeckParams struct {
	Title       string
	Description string
	UserID      uuid.UUID
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck, arg.Title, arg.Description, arg.UserID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteDecks = `-- name: DeleteDecks :exec
  DELETE FROM decks
`

func (q *Queries) DeleteDecks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDecks)
	return err
}
