// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (
 id,
 title,
 description,
 created_at,
 user_id,
 total_reviews
) VALUES (
  gen_random_uuid(),
	$1,
	$2,
  NOW(),
  $3,
  0
) RETURNING 
 id,
 title,
 description,
 created_at,
 user_id,
 total_reviews
`

type CreateDeckParams struct {
	Title       string
	Description string
	UserID      uuid.UUID
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck, arg.Title, arg.Description, arg.UserID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UserID,
		&i.TotalReviews,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
  DELETE FROM decks
  WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeck, id)
	return err
}

const deleteDecks = `-- name: DeleteDecks :exec
  DELETE FROM decks
`

func (q *Queries) DeleteDecks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDecks)
	return err
}

const getDeckById = `-- name: GetDeckById :one
  SELECT id, title, description, created_at, user_id, total_reviews FROM decks
  WHERE id = $1
`

func (q *Queries) GetDeckById(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeckById, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UserID,
		&i.TotalReviews,
	)
	return i, err
}

const getDecksByUser = `-- name: GetDecksByUser :many
  SELECT id, title, description, created_at, user_id, total_reviews FROM decks
  WHERE user_id = $1
  ORDER BY created_at ASC
`

func (q *Queries) GetDecksByUser(ctx context.Context, userID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, getDecksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UserID,
			&i.TotalReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks
SET title  = $1,
    description  = $2,
    total_reviews  = $3
WHERE id = $4
RETURNING id, title, description, created_at, user_id, total_reviews
`

type UpdateDeckParams struct {
	Title        string
	Description  string
	TotalReviews int32
	ID           uuid.UUID
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, updateDeck,
		arg.Title,
		arg.Description,
		arg.TotalReviews,
		arg.ID,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UserID,
		&i.TotalReviews,
	)
	return i, err
}
