// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID               uuid.UUID
	FrontContent     string
	BackContent      string
	Interval         int32
	Target           int32
	EaseFactor       float64
	RepetitionsCount int32
	LastReviewedAt   sql.NullTime
	LastReviewedNum  int32
	CreatedAt        time.Time
	DeckID           uuid.UUID
	Tempo            int32
	PerfectStreak    int32
	BadStreak        int32
}

type Deck struct {
	ID               uuid.UUID
	Title            string
	Description      string
	CreatedAt        time.Time
	UserID           uuid.UUID
	TotalReviews     int32
	TempoIntervalUp  int32
	TempoIntervalDn  int32
	PerfectThreshold int32
	BadThreshold     int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
