// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID               uuid.UUID
	FrontContent     string
	BackContent      string
	Interval         int32
	EaseFactor       float64
	RepetitionsCount int32
	LastReviewedAt   sql.NullTime
	CreatedAt        time.Time
	DeckID           uuid.UUID
}

type Deck struct {
	ID          uuid.UUID
	Title       string
	Description string
	CreatedAt   time.Time
	UserID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
